name: Check PR description
author: jstrzebonski
branding:
  icon: "search"
  color: "green"
description: Check PR title and description format
inputs:
  pr_branch:
    description: "PR's branch name"
    required: true
    default: ""
  pr_title:
    description: "Title of the PR"
    required: true
    default: ""
  pr_description:
    description: "Description of the PR"
    required: true
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
